version: '3'
services:
  statsd-cloudwatch:
    build: .
    environment:
      AWS_REGION: ${AWS_REGION}
      AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      CLOUDWATCH_NAMESPACE: ${CLOUDWATCH_NAMESPACE}
    ports:
      - 8125:8125/tcp
      - 8125:8125/udp
